version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - errcheck
  exclusions:
    rules:
      - text: "MarkFlagRequired"
        linters:
          - errcheck
      - text: "fmt\\.Fprint"
        linters:
          - errcheck
      - text: "fmt\\.Print"
        linters:
          - errcheck
      - text: "Flush"
        linters:
          - errcheck
      - text: "enc\\.Encode"
        linters:
          - errcheck
      - text: "Error return value of .*(Close|close).*is not checked"
        linters:
          - errcheck
      - text: "ShowSummary"
        linters:
          - errcheck
      - text: "RegisterTLSConfig"
        linters:
          - errcheck
      - text: "os\\.MkdirAll"
        linters:
          - errcheck
      - text: "os\\.Remove"
        linters:
          - errcheck
      - text: "os\\.Chtimes"
        linters:
          - errcheck
      - text: "filepath\\.Walk"
        linters:
          - errcheck
      - text: "saveMetadata"
        linters:
          - errcheck
